export enum Custom_Names {
    NAVMESH = "navmesh"
}

export enum Custom_Events {
    SHOT_FIRED = "SHOT_FIRED",
    UNLOAD_ASSET = "UNLOAD_ASSET",
    YOYO_HIT_PLAYER = "YOYO_HIT_PLAYER",
    YOYO_HIT_ENEMY = "YOYO_HIT_ENEMY",
    HIT_ENEMY = "HIT_ENEMY",
    ENEMY_DEATH = "ENEMY_DEATH",
    HEAL = "HEAL",
    PLAYER_DAMAGED = "PLAYER_DAMAGED",
    PLAYER_DEATH = "PLAYER_DEATH",
    PAUSE_EVENT = "PAUSE_EVENT",
    COMPLETE_OBJECTIVE = "COMPLETE_OBJECTIVE",
    YOYO_RETURNED = "YOYO_RETURNED",
    IN_CINEMATIC = "IN_CINEMATIC",
    PLAY_SOUND = "PLAY_SOUND",
    STONE_HIT_PLAYER = "STONE_HIT_PLAYER",
    STONE_HIT_ENEMY = "STONE_HIT_ENEMY",
    STONE_FIRED = "STONE_FIRED"
}

export enum Custom_Statuses {
    IN_RANGE = "IN_RANGE",
    LOW_HEALTH = "LOW_HEALTH",
    CAN_RETREAT = "CAN_RETREAT",
    CAN_BERSERK = "CAN_BERSERK",
    REACHED_GOAL = "GOAL"
}